# File: matlab-ts-bin/README.org
# Copyright (C) 2001-2025 Free Software Foundation, Inc.

#+startup: showall
#+startup: logdone
#+startup: inlineimages
#+startup: latexpreview
#+options: ^:{}    # a_{b} for subscript, a^{b} for superscript, leave a_b and a^b as is.
#+options: toc:2   # toc:nil == no toc, toc:1 == one level, toc:2 == two levels, etc.

#+latex_header: \usepackage[margin=0.25in]{geometry}
#+latex_header: \usepackage{parskip}
#+latex_header: \usepackage{svg}
#+latex_header: \sloppy

#+title:  matlab-ts-bin/README.org
#+author: John Ciolfi
#+date:   Nov-24-2025

Builds of https://github.com/acristoffers/tree-sitter-matlab

We use the following subdirectory naming convention:

: ./matlab-ts-abiNN/YYYYMMDD-SHA1/ARCH/

where

 - =NN= is the tree-sitter ABI version. For example =NN==14= for Emacs 30.

 - =YYYYMMDD= corresponds to the year, month, day of the
   https://github.com/acristoffers/tree-sitter-matlab commit =SHA1=

 - =ARCH= is from the MATLAB command, =computer('arch')= where we have:

   + glnxa64 :: GNU/Linux running on x86_64 (=uname -m=)

     Build:

     #+begin_src bash
       cd ./matlab-ts-abiNN/YYYYMMDD-SHA1/src
       cc -fPIC -O -c -I. parser.c
       cc -fPIC -O -c -I. scanner.c
       cc -fPIC -shared parser.o scanner.o -o ../glnxa64/libtree-sitter-matlab.so
     #+end_src
     
   + maca64 :: MacOS running on arm64 (=uname -m=)

     #+begin_src bash
       cd ./matlab-ts-abiNN/YYYYMMDD-SHA1/src
       cc -fPIC -O -c -I. parser.c
       cc -fPIC -O -c -I. scanner.c
       cc -fPIC -shared parser.o scanner.o -o ../maca64/libtree-sitter-matlab.dylib

       # Remove hardcoded absolute path from the *.dylib. This is not necessarily needed by Emacs because
       # dylib is dynamically loaded. It is needed if people want to use this library in other executables
       # with explicit linking when using rpath linker option: -Wl,-rpath,ABS_MATLAB_DYLIB_DIR (where
       # ABS_MATLAB_DYLIB_DIR is where libtree-sitter-matlab.dylib is placed).

       cd ../maca64

       # The Mac embeds the loader instructions in the executables, which we can see via:loader uses via:
       otool -l libtree-sitter-matlab.dylib > otool_l_initial.tmp.txt

       # Using otool -L we see the paths of the library that the dylib uses, which is an absolute path
       # (where the library lives), /abs/path/to/libtree-sitter-matlab.dylib
       otool -L libtree-sitter-matlab.dylib

       # Every macOS dynamic library has a built-in ID string, in our case an absolute file path that
       # dictates where other applications should look for it at runtime. install_name_tool -id lets you
       # rewrite this embedded path, to use relative, @rpath:
       install_name_tool -id "@rpath/libtree-sitter-matlab.dylib" libtree-sitter-matlab.dylib

       # Now tell the dynamic linker (dyld) where to look for @rpath reference by leveraging @loader_path
       # which is relative to the directory containing the library currently being loaded.
       # See the dyld man page for @loader_path information.
       install_name_tool -add_rpath "@loader_path/." libtree-sitter-matlab.dylib

       # Check via otool -L libtree-sitter-matlab.dylib which should display something like
       # libtree-sitter-matlab.dylib:
       # 	@rpath/libtree-sitter-matlab.dylib (compatibility version 0.0.0, current version 0.0.0)
       # 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
       otool -L libtree-sitter-matlab.dylib

       # View the embedded RPATH search directories using below which should display something like
       #       cmd LC_RPATH
       #   cmdsize 32
       #      path @loader_path/. (offset 12)
       otool -l libtree-sitter-matlab.dylib | tee otool_l_updated.tmp.txt | grep -A 2 LC_RPATH

       # Loader instruction diff
       diff -u otool_l_initial.tmp.txt  otool_l_updated.tmp.txt 

       # cleanup
       rm *.tmp.txt
     #+end_src

   + maci64 :: MacOS running on x86_64 (=uname -m=). Note MATLAB release, R2025b, is the last
     release that supports Intel/AMD based MacOS systems.  Follow the same steps as maca64,
     replacing maca64 with maci64.

   + win64 :: Microsoft Windows running on Intel/AMD (=echo %PROCESSOR_ARCHITECTURE%= is AMD64 in a
     Command Window)

     #+begin_src bash
       "C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat"
       cd ./matlab-ts-abiNN/YYYYMMDD-SHA1/src
       cl /LD /I src\tree_sitter parser.c scanner.c /link /out:..\win64\libtree-sitter-matlab.dll
     #+end_src

We are using this convention instead of the tree-sitter-matlab release number to make things more
flexible.  This convention lets us deploy based on commits rather than release numbers.

We also save the source in a src directory under each build subdirectory.

# LocalWords:  showall logdone inlineimages latexpreview usepackage parskip svg abi NN YYYYMMDD SHA
# LocalWords:  uname maca maci MSYS libtree dylib VC vcvars otool rpath dyld tmp usr cmdsize Wl
